"""
Bounding box + centroid detector for the target object. Two interchangeable
backends, selected by config.DETECTOR_BACKEND:

  "color" (default) — classical computer vision, no training needed. HSV
    color thresholding + contour finding. Good default because the target
    is a single, visually consistent color against a fairly plain
    background. See calibrate_color.py to tune it for your camera/lighting.

  "neural_net" — a small trained CNN (detector_model.py) predicts the same
    centroid/size/visibility instead of thresholding colors. Trained on
    pseudo-labels generated BY the color detector itself (see
    generate_pseudo_labels.py + train_detector.py) — so it's only useful
    once you have a color detector that already works reasonably well, and
    it can only get as good as those labels were. The appeal is
    generalizing past the color threshold's blind spots (lighting drift,
    partial occlusion, a second similarly-colored object) *if* your
    training images actually contain that variety.

Either way, everything downstream (drive.py's control loop) only depends
on get_target() returning a centroid + size in this same dict shape — it
never needs to know which backend produced it. This also means it never
learns steering directly: the sign of the turn command always comes from
a measured (or predicted) pixel position, not from an imitated
human-driving correlation, which is what let the wrong-direction-turn
problem creep into the original end-to-end model.
"""

import cv2
import numpy as np
from config import HSV_LOWER, HSV_UPPER, MIN_TARGET_AREA_FRACTION, DETECTOR_BACKEND, PERCEPTION_MODEL_PATH


def get_target(frame, hsv_lower=HSV_LOWER, hsv_upper=HSV_UPPER,
               min_area_fraction=MIN_TARGET_AREA_FRACTION):
    """Find the target in `frame`. Dispatches to the color-threshold detector
    or the trained perception model based on config.DETECTOR_BACKEND — drive.py
    doesn't need to know or care which one is active, since both return the
    same dict shape.

    generate_pseudo_labels.py and calibrate_color.py deliberately do NOT use
    this dispatcher — they call get_target_color() directly below, always,
    regardless of DETECTOR_BACKEND. Those two tools exist specifically to
    bootstrap/tune the color method itself, which would break if
    DETECTOR_BACKEND is set to "neural_net" (there's no trained model yet
    the first time you ever run them, and calibrate_color.py's whole point
    is tuning HSV values the dispatcher would otherwise ignore).
    """
    if DETECTOR_BACKEND == "neural_net":
        return _get_target_nn(frame)
    return get_target_color(frame, hsv_lower, hsv_upper, min_area_fraction)


_nn_model = None
_nn_transform = None
_nn_device = None


def _load_nn():
    """Lazy-load the perception model on first use, so importing detect.py
    doesn't require torch to be installed if you're only using the color
    backend."""
    global _nn_model, _nn_transform, _nn_device
    if _nn_model is not None:
        return
    import torch
    from torchvision import transforms
    from detector_model import DetectorModel
    from config import IMG_SIZE

    checkpoint = torch.load(PERCEPTION_MODEL_PATH, map_location="cpu")
    _nn_device = ("mps" if torch.backends.mps.is_available() else
                  "cuda" if torch.cuda.is_available() else "cpu")
    _nn_model = DetectorModel().to(_nn_device)
    _nn_model.load_state_dict(checkpoint["state_dict"])
    _nn_model.eval()
    _nn_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])


def _get_target_nn(frame, visible_threshold=0.5):
    """Same return contract as get_target_color, but from the trained
    perception model (detector_model.py / train_detector.py) instead of a
    color threshold. Train that model first — see train_detector.py."""
    import torch
    from PIL import Image

    _load_nn()
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(rgb)
    tensor = _nn_transform(pil_img).unsqueeze(0).to(_nn_device)

    with torch.no_grad():
        cx_norm, cy_norm, area_frac, visible_logit = _nn_model(tensor)
        cx_norm, cy_norm, area_frac, visible_logit = cx_norm[0], cy_norm[0], area_frac[0], visible_logit[0]
        visible_prob = torch.sigmoid(visible_logit)

    if float(visible_prob) < visible_threshold:
        return None

    h, w = frame.shape[:2]
    cx_norm, cy_norm, area_frac = float(cx_norm), float(cy_norm), float(area_frac)
    # Reconstruct an approximate bbox from area_frac for drawing/debugging —
    # the model doesn't predict width/height separately, so this assumes a
    # roughly square-ish box just for visualization purposes.
    approx_side = int((area_frac * h * w) ** 0.5)
    cx_px = int(w / 2 + cx_norm * (w / 2))
    cy_px = int(h / 2 + cy_norm * (h / 2))
    bbox = (max(0, cx_px - approx_side // 2), max(0, cy_px - approx_side // 2),
            approx_side, approx_side)

    return {"cx_norm": cx_norm, "cy_norm": cy_norm, "area_frac": area_frac, "bbox": bbox, "mask": None}


def get_target_color(frame, hsv_lower=HSV_LOWER, hsv_upper=HSV_UPPER, min_area_fraction=MIN_TARGET_AREA_FRACTION):
    """Classical detector: HSV color thresholding + largest contour. This is
    the DETECTOR_BACKEND = "color" implementation (the default) — see the
    module docstring above for why this was the starting choice, and
    generate_pseudo_labels.py / train_detector.py for how to train the
    "neural_net" alternative using this detector's own output as labels."""
    h, w = frame.shape[:2]
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, hsv_lower, hsv_upper)

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    largest = max(contours, key=cv2.contourArea)
    area = cv2.contourArea(largest)
    frame_area = h * w
    if area < min_area_fraction * frame_area:
        return None

    x, y, bw, bh = cv2.boundingRect(largest)
    M = cv2.moments(largest)
    cx = M["m10"] / M["m00"]
    cy = M["m01"] / M["m00"]

    return {
        "cx_norm": (cx - w / 2) / (w / 2),
        "cy_norm": (cy - h / 2) / (h / 2),
        "area_frac": area / frame_area,
        "bbox": (x, y, bw, bh),
        "mask": mask,  # handy for calibrate_color.py's live preview
    }


def draw_debug(frame, target):
    """Draw the bounding box + centroid on a copy of frame, for a HUD/preview."""
    out = frame.copy()
    h, w = out.shape[:2]
    if target is not None:
        x, y, bw, bh = target["bbox"]
        cv2.rectangle(out, (x, y), (x + bw, y + bh), (0, 255, 0), 2)
        cx_px = int(w / 2 + target["cx_norm"] * (w / 2))
        cy_px = int(h / 2 + target["cy_norm"] * (h / 2))
        cv2.drawMarker(out, (cx_px, cy_px), (0, 0, 255), cv2.MARKER_CROSS, 20, 2)
        cv2.putText(out, f"area={target['area_frac']:.3f} cx={target['cx_norm']:+.2f}",
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
    else:
        cv2.putText(out, "TARGET NOT FOUND", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
    cv2.drawMarker(out, (w // 2, h // 2), (255, 255, 0), cv2.MARKER_CROSS, 12, 1)
    return out
