"""
Bounding box + centroid detector for the target object. Two interchangeable
backends, selected by config.DETECTOR_BACKEND:

  "color" (default) — classical computer vision, no training needed. HSV
    color thresholding + contour finding. Good default because the target
    is a single, visually consistent color against a fairly plain
    background. See calibrate_color.py to tune it for your camera/lighting.

  "grid" — a small trained grid detector (grid_detector_model.py) predicts
    a full bounding box (not just a centroid point) using a simplified,
    single-object version of YOLO's core idea. Trained on pseudo-labels
    generated BY the color detector itself (see generate_pseudo_boxes.py +
    train_grid_detector.py) — so it's only useful once the color detector
    already works reasonably well, and it can only get as good as those
    labels were.

Either way, everything downstream (drive.py's control loop) only depends
on get_target() returning a centroid + size in this same dict shape — it
never needs to know which backend produced it, or whether that backend
found the answer via a color mask or a trained grid of predictions.
"""

import cv2
import numpy as np
from config import HSV_LOWER, HSV_UPPER, MIN_TARGET_AREA_FRACTION, DETECTOR_BACKEND, PERCEPTION_MODEL_PATH


def get_target(frame, hsv_lower=HSV_LOWER, hsv_upper=HSV_UPPER,
               min_area_fraction=MIN_TARGET_AREA_FRACTION):
    """Find the target in `frame`. Dispatches to the color-threshold detector
    or the trained grid detector based on config.DETECTOR_BACKEND — drive.py
    doesn't need to know or care which one is active, since both return the
    same dict shape.

    generate_pseudo_boxes.py and calibrate_color.py deliberately do NOT use
    this dispatcher — they call get_target_color() directly, always,
    regardless of DETECTOR_BACKEND, since those two tools exist specifically
    to bootstrap/tune the color method itself.
    """
    if DETECTOR_BACKEND == "grid":
        return _get_target_grid(frame)
    return get_target_color(frame, hsv_lower, hsv_upper, min_area_fraction)


_grid_model = None
_grid_transform = None
_grid_device = None


def _load_grid_model():
    """Lazy-load the grid detector on first use, so importing detect.py
    doesn't require torch to be installed if you're only using the color
    backend."""
    global _grid_model, _grid_transform, _grid_device
    if _grid_model is not None:
        return
    import torch
    from torchvision import transforms
    from grid_detector_model import GridDetector
    from config import IMG_SIZE

    checkpoint = torch.load(PERCEPTION_MODEL_PATH, map_location="cpu")
    _grid_device = ("mps" if torch.backends.mps.is_available() else
                    "cuda" if torch.cuda.is_available() else "cpu")
    _grid_model = GridDetector().to(_grid_device)
    _grid_model.load_state_dict(checkpoint["state_dict"])
    _grid_model.eval()
    _grid_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])


def _get_target_grid(frame, confidence_threshold=0.5):
    """Same return contract as get_target_color, but from the trained grid
    detector instead of a color threshold. Train that model first — see
    train_grid_detector.py."""
    import torch
    from grid_detector_model import decode_prediction
    from PIL import Image

    _load_grid_model()
    h, w = frame.shape[:2]
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    pil_img = Image.fromarray(rgb)
    tensor = _grid_transform(pil_img).unsqueeze(0).to(_grid_device)

    with torch.no_grad():
        confidence, x_offset, y_offset, bw, bh = _grid_model(tensor)

    result = decode_prediction(confidence[0], x_offset[0], y_offset[0],
                                bw[0], bh[0], confidence_threshold)
    if result is None:
        return None

    bbox = (
        int((result["cx_frac"] - result["w_frac"] / 2) * w),
        int((result["cy_frac"] - result["h_frac"] / 2) * h),
        int(result["w_frac"] * w),
        int(result["h_frac"] * h),
    )
    return {
        "cx_norm": result["cx_norm"],
        "cy_norm": result["cy_norm"],
        "area_frac": result["area_frac"],
        "bbox": bbox,
        "mask": None,
    }


def get_target_color(frame, hsv_lower=HSV_LOWER, hsv_upper=HSV_UPPER, min_area_fraction=MIN_TARGET_AREA_FRACTION):
    """Classical detector: HSV color thresholding + largest contour. This is
    the DETECTOR_BACKEND = "color" implementation (the default) — see the
    module docstring above for why this was the starting choice, and
    generate_pseudo_boxes.py / train_grid_detector.py for how to train the
    "grid" alternative using this detector's own output as labels."""
    h, w = frame.shape[:2]
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(hsv, hsv_lower, hsv_upper)

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return None

    largest = max(contours, key=cv2.contourArea)
    area = cv2.contourArea(largest)
    frame_area = h * w
    if area < min_area_fraction * frame_area:
        return None

    x, y, bw, bh = cv2.boundingRect(largest)
    M = cv2.moments(largest)
    cx = M["m10"] / M["m00"]
    cy = M["m01"] / M["m00"]

    return {
        "cx_norm": (cx - w / 2) / (w / 2),
        "cy_norm": (cy - h / 2) / (h / 2),
        "area_frac": area / frame_area,
        "bbox": (x, y, bw, bh),
        "mask": mask,
    }


def draw_debug(frame, target):
    """Draw the bounding box + centroid on a copy of frame, for a HUD/preview."""
    out = frame.copy()
    h, w = out.shape[:2]
    if target is not None:
        x, y, bw, bh = target["bbox"]
        cv2.rectangle(out, (x, y), (x + bw, y + bh), (0, 255, 0), 2)
        cx_px = int(w / 2 + target["cx_norm"] * (w / 2))
        cy_px = int(h / 2 + target["cy_norm"] * (h / 2))
        cv2.drawMarker(out, (cx_px, cy_px), (0, 0, 255), cv2.MARKER_CROSS, 20, 2)
        cv2.putText(out, f"area={target['area_frac']:.3f} cx={target['cx_norm']:+.2f}",
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)
    else:
        cv2.putText(out, "TARGET NOT FOUND", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
    cv2.drawMarker(out, (w // 2, h // 2), (255, 255, 0), cv2.MARKER_CROSS, 12, 1)
    return out
