"""
Train the perception model (detector_model.py) to predict target
centroid/size/visibility from an image, using pseudo-labels generated by
generate_pseudo_labels.py (the color-threshold detector's own output).

Run generate_pseudo_labels.py first:
    python generate_pseudo_labels.py data/images data/pseudo_labels.csv

Then:
    python train_detector.py data/images data/pseudo_labels.csv

This mirrors train.py's session-aware split (if the images came from
collect_data.py and labels.csv has a session_id column, sessions are held
out whole for validation) and reuses the same reasoning: at 10Hz,
neighboring frames are nearly identical, so a random per-frame split would
leak near-duplicates across train/val.

Loss:
  - cx_norm, area_frac: MSE, but ONLY on frames where visible=1 (a
    not-visible frame has no meaningful position/size to regress to —
    including it would just teach the model to output whatever the
    placeholder 0/0 values were, which is wrong).
  - visible: binary cross-entropy on every frame (this target is
    meaningful whether or not the object is visible).
"""

import sys
import csv
import random
import torch
import torch.nn as nn
from collections import defaultdict
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import matplotlib.pyplot as plt
from pathlib import Path
from detector_model import DetectorModel
from config import IMG_SIZE

MODEL_OUT = "detector_model.pt"
EPOCHS = 12
BATCH = 30
LR_HEAD = 1e-3
LR_BACKBONE = 1e-4
UNFREEZE_LAST_N_BLOCKS = 2
VAL_FRACTION = 0.2
SEED = 42
VISIBILITY_LOSS_WEIGHT = 0.5  # position/size loss is the main signal; visibility is secondary


class DetectorDataset(Dataset):
    def __init__(self, img_dir, rows, transform):
        self.img_dir = Path(img_dir)
        self.rows = rows  # list of (fname, cx_norm, area_frac, visible)
        self.transform = transform

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        fname, cx, area, visible = self.rows[idx]
        img = Image.open(self.img_dir / fname).convert("RGB")
        img = self.transform(img)
        target = torch.tensor([float(cx), float(area), float(visible)], dtype=torch.float32)
        return img, target


transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    # No horizontal flip: flipping would invert cx_norm's sign.
    transforms.ColorJitter(brightness=0.3, contrast=0.3),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])


def masked_position_loss(cx_pred, area_pred, cx_true, area_true, visible_true):
    """MSE on cx_norm/area_frac, counted only where visible_true == 1."""
    mask = visible_true
    n_visible = mask.sum().clamp(min=1)
    cx_err = ((cx_pred - cx_true) ** 2) * mask
    area_err = ((area_pred - area_true) ** 2) * mask
    return (cx_err.sum() + area_err.sum()) / (2 * n_visible)


def load_rows(labels_csv):
    with open(labels_csv) as f:
        reader = csv.reader(f)
        header = next(reader)
        rows = [row for row in reader]
    return header, rows


def session_aware_split(img_dir, labels_csv):
    """Reuses the session_id column written by the updated collect_data.py
    if present (so validation holds out whole drives, not random frames).
    Falls back to a random per-frame split with a warning if it's missing
    or there's only one session — same reasoning as train.py.

    pseudo_labels.csv (this file) has columns: filename,cx_norm,area_frac,
    visible — it never has session_id itself. Session membership is
    borrowed from a sibling labels.csv (the one collect_data.py wrote),
    matched by filename."""
    header, rows = load_rows(labels_csv)
    sibling_labels = Path(labels_csv).parent / "labels.csv"
    session_by_fname = {}
    if sibling_labels.exists():
        with open(sibling_labels) as f:
            r = csv.reader(f)
            h = next(r)
            if "session_id" in h:
                sid_idx = h.index("session_id")
                for row in r:
                    session_by_fname[row[0]] = row[sid_idx]

    rows_by_session = defaultdict(list)
    for fname, cx, area, visible in rows:
        sid = session_by_fname.get(fname, "0")
        rows_by_session[sid].append((fname, cx, area, visible))

    if not session_by_fname:
        print("NOTE: no matching labels.csv with session_id found next to "
              f"{labels_csv} — falling back to a random per-frame split "
              "(val loss will be a bit optimistic, but this matters far "
              "less here than it did for the motor-speed model, since "
              "consecutive frames having similar target position isn't a "
              "shortcut the way 'consecutive frames have similar zero "
              "motor command' was).")

    session_ids = list(rows_by_session.keys())
    rng = random.Random(SEED)
    rng.shuffle(session_ids)

    if len(session_ids) < 2:
        only_rows = next(iter(rows_by_session.values()))
        idx = list(range(len(only_rows)))
        rng.shuffle(idx)
        n_val = max(1, int(VAL_FRACTION * len(idx)))
        val_idx, train_idx = set(idx[:n_val]), set(idx[n_val:])
        return [only_rows[i] for i in train_idx], [only_rows[i] for i in val_idx]

    n_val_sessions = max(1, int(VAL_FRACTION * len(session_ids)))
    n_val_sessions = min(n_val_sessions, len(session_ids) - 1)
    val_sessions = set(session_ids[:n_val_sessions])
    train_rows, val_rows = [], []
    for sid, sid_rows in rows_by_session.items():
        (val_rows if sid in val_sessions else train_rows).extend(sid_rows)
    return train_rows, val_rows


def main(img_dir, labels_csv):
    train_rows, val_rows = session_aware_split(img_dir, labels_csv)
    print(f"Frames: {len(train_rows)} train / {len(val_rows)} val")

    train_ds = DetectorDataset(img_dir, train_rows, transform)
    val_ds = DetectorDataset(img_dir, val_rows, transform)
    train_loader = DataLoader(train_ds, batch_size=BATCH, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=BATCH, shuffle=False, num_workers=0)

    device = ("mps" if torch.backends.mps.is_available() else
              "cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on: {device}\n")

    model = DetectorModel().to(device)
    for p in model.features.parameters():
        p.requires_grad = False
    backbone_finetune_params = []
    for block in list(model.features.children())[-UNFREEZE_LAST_N_BLOCKS:]:
        for p in block.parameters():
            p.requires_grad = True
            backbone_finetune_params.append(p)

    head_params = list(model.position_squeeze.parameters()) + list(model.global_head.parameters())
    optimizer = torch.optim.Adam([
        {"params": head_params, "lr": LR_HEAD},
        {"params": backbone_finetune_params, "lr": LR_BACKBONE},
    ])
    bce = nn.BCEWithLogitsLoss()

    train_losses, val_losses = [], []
    best_val_loss = float("inf")

    for epoch in range(EPOCHS):
        model.train()
        train_loss = 0.0
        for imgs, targets in train_loader:
            imgs, targets = imgs.to(device), targets.to(device)
            cx_true, area_true, visible_true = targets[:, 0], targets[:, 1], targets[:, 2]

            optimizer.zero_grad()
            cx_pred, cy_pred, area_pred, visible_logit = model(imgs)

            pos_loss = masked_position_loss(cx_pred, area_pred, cx_true, area_true, visible_true)
            vis_loss = bce(visible_logit, visible_true)
            loss = pos_loss + VISIBILITY_LOSS_WEIGHT * vis_loss

            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for imgs, targets in val_loader:
                imgs, targets = imgs.to(device), targets.to(device)
                cx_true, area_true, visible_true = targets[:, 0], targets[:, 1], targets[:, 2]
                cx_pred, cy_pred, area_pred, visible_logit = model(imgs)
                pos_loss = masked_position_loss(cx_pred, area_pred, cx_true, area_true, visible_true)
                vis_loss = bce(visible_logit, visible_true)
                val_loss += (pos_loss + VISIBILITY_LOSS_WEIGHT * vis_loss).item()

        avg_train = train_loss / len(train_loader)
        avg_val = val_loss / len(val_loader)
        train_losses.append(avg_train)
        val_losses.append(avg_val)
        print(f"Epoch {epoch + 1:2d}/{EPOCHS}  train={avg_train:.4f}  val={avg_val:.4f}")

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            torch.save({"state_dict": model.state_dict()}, MODEL_OUT)
            print(f"           ↑ best model saved → {MODEL_OUT}")

    plt.plot(train_losses, label="train")
    plt.plot(val_losses, label="val")
    plt.title("Perception model loss (position MSE + visibility BCE)")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.tight_layout()
    plt.savefig("detector_training_curve.png", dpi=150)
    print(f"\nDone. Best validation loss: {best_val_loss:.4f}")


if __name__ == "__main__":
    if len(sys.argv) == 3:
        img_dir, labels_csv = sys.argv[1], sys.argv[2]
    elif len(sys.argv) == 1:
        img_dir = Path(__file__).parent / "data" / "images"
        labels_csv = Path(__file__).parent / "data" / "pseudo_labels.csv"
        print(f"No arguments given — using defaults:\n  images_dir  = {img_dir}\n  labels_csv  = {labels_csv}\n")
    else:
        raise SystemExit("Usage: python train_detector.py <images_dir> <pseudo_labels_csv>")
    main(img_dir, labels_csv)
