"""
Step 2 — Drive by whistle pitch.

Reads the microphone at ~20 Hz, detects the dominant pitch via FFT,
maps it to a motor command, and drives the double motor accordingly.
Silence (RMS below threshold) always stops the motors.

Loads pitch_bands.json if it exists (generated by calibrate.py),
otherwise falls back to the defaults in config.py.

Press Ctrl+C to stop.

macOS note: you may need to grant Terminal microphone access in
  System Settings → Privacy & Security → Microphone.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

import json
import queue
import numpy as np
import sounddevice as sd
from config import (SERIAL, SAMPLE_RATE, CHUNK_SIZE, AMPLITUDE_THRESHOLD,
                    DEFAULT_PITCH_BANDS, MOTOR_MAP)
from pitch import detect, freq_to_command
from lelib import doubleMotor
from miclib import pick_mic

BANDS_FILE = Path(__file__).parent / "pitch_bands.json"

# Load calibrated bands if available, else use defaults
if BANDS_FILE.exists():
    with open(BANDS_FILE) as f:
        raw = json.load(f)
    pitch_bands = [tuple(b) for b in raw]
    print(f"Loaded calibrated bands from {BANDS_FILE}")
else:
    pitch_bands = DEFAULT_PITCH_BANDS
    print("No pitch_bands.json found — using default bands from config.py")
    print("Run calibrate.py to tune the bands to your whistle.\n")

print("Pitch bands:")
for lo, hi, cmd in pitch_bands:
    left, right = MOTOR_MAP[cmd]
    print(f"  {lo:5d}–{hi:5d} Hz  →  {cmd:<10}  (L={left:+4d}, R={right:+4d})")

dm = doubleMotor()
print("\nConnecting to double motor...")
dm.connect(SERIAL)
print("Connected. Whistle to drive. Ctrl+C to quit.\n")

mic_device = pick_mic()

audio_q = queue.Queue(maxsize=4)  # small buffer — we want the freshest frame

def _audio_callback(indata, frames, t, status):
    if not audio_q.full():
        audio_q.put(indata.copy())


# ── Column header ─────────────────────────────────────────────────────────────
print(f"{'Hz':>6}  {'rms':>6}  {'command':<10}  {'L':>5}  {'R':>5}")
print("─" * 44)

last_command = None

with sd.InputStream(samplerate=SAMPLE_RATE, channels=1,
                    blocksize=CHUNK_SIZE, dtype="float32",
                    device=mic_device,
                    callback=_audio_callback):
    try:
        while True:
            chunk = audio_q.get()
            hz, rms = detect(chunk)

            if rms < AMPLITUDE_THRESHOLD:
                command = "stop"
                hz_str  = "—"
            else:
                command = freq_to_command(hz, pitch_bands)
                hz_str  = f"{hz:.0f}"

            left, right = MOTOR_MAP[command]

            # Only send a motor command when it changes — avoids spamming BLE
            if command != last_command:
                dm.movement_move_tank(left, right)
                last_command = command

            print(f"{hz_str:>6}  {rms:>6.3f}  {command:<10}  {left:>+5d}  {right:>+5d}",
                  flush=True)

    except KeyboardInterrupt:
        pass
    finally:
        dm.stop()
        print("\nStopped.")
